#! /bin/sh

#
# Script to start a local proxy with CNTLM
#

# Read proxy username
echo -n "Username: "
read USER

# Start CNTLM service
cntlm -I -u $USER

# Export proxy configuration
export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128
